#
# ArtifactHub: https://artifacthub.io/packages/helm/longhorn/longhorn
# GitHub: https://github.com/longhorn/longhorn/tree/master/chart
# Default Values: https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
#
global:
  nodeSelector:
    node-role: storage

defaultSettings:
  systemManagedComponentsNodeSelector: "node-role:storage"
  storageReservedPercentageForDefaultDisk: 5
  defaultDataLocality: best-effort

persistence:
  defaultClass: false

longhornManager: {}

longhornDriver: {}

longhornUI:
  replicas: 1

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: nginx-ssl
  host: "${STORAGE_DOMAIN}"
  tls: true
  tlsSecret: longhorn-tls

metrics:
  serviceMonitor:
    enabled: false
